{% set version = "0.14.1" %}

package:
  name: fasteners
  version: {{ version }}

source:
  fn: fasteners-v{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/fasteners/fasteners-{{ version }}.tar.gz
  md5: fcb13261c9b0039d9b1c4feb9bc75e04

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six
    - monotonic >=0.1

  run:
    - python
    - six
    - monotonic >=0.1

test:
  imports:
    - fasteners
    - fasteners.tests

about:
  home: https://github.com/harlowja/fasteners
  license: Apache License Version 2.0
  summary: A python package that provides useful locks.

extra:
  recipe-maintainers:
    - alimanfoo
