{% set name = "fasteners" %}
{% set version = "0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55dce8792a41b56f727ba6e123fcaee77fd87e638a6863cec00007bfea84c8d8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - fasteners
    - fasteners.lock
    - fasteners.process_lock
    - fasteners.process_mechanism
    - fasteners.version
  requires:
    - pip
    - pytest
    - diskcache
    - more-itertools
    - eventlet
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/harlowja/fasteners
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cross-platform locks for threads and processes.
  description: Python standard library provides an Exclusive Lock for threads and Exclusive Lock 
    for processes spawned by multiprocessing module. fasteners provides additional three synchronization primitives 
    Exclusive Lock for independent processes, Readers Writer Lock for independent processes ,Readers Writer Lock for threads
  dev_url: https://github.com/harlowja/fasteners
  doc_url: https://fasteners.readthedocs.io/

extra:
  recipe-maintainers:
    - alimanfoo