travis:
  secure:
    BINSTAR_TOKEN: J6M0RAIJmNYzOMYV5prrlk+TczEdLf10TeucOo0fRJ6DhPQl114V2nIxZ36M2GDm506rf5KZ2hGXyfyjCaV0b/P9RdHsyYKc8AkyQ+LfakZ0N+lafmWK0MoK/jFWNi9HMyQOhUTY2v3Ui9Cj0HTnCr2uIhihxPzT4AsJjxtr0/TjalcBoBkCyJQYPMmnT++G0d3kPO5narllqUNARfuQ7UG3yrT0mTKpwgHLFQW3Uwo/VTp2Xf5FzgraldWeNWQBMQ/jOaCUwRnAwuimBFdXUusfkCcq1tnIRsN609hiMdZ4bF+2gHWQBhFPvRv+MpcE/xSOTOX98svp3zw9UorLyJ3D1r2pHR99918AIi4ZNMtP/L3uJDgJPHeK9rf5FqnQqcmhF4UOuJbLjvIJiDK0mm5FspY4dBQI6KDFTxWRaVp2dVdvT5C0T2y7Qa7CybQlkk2cp9GTXYWubl0B9hxGJQHFzHBB1CW9jSeRxlxHp9PbLQyFJDbbghbxTUeBHuEuzqE6CO3Pz0Ksv+XHGj2ZaUrpWSgw32vC8nZNmlixGhEr8k70aVXf5PBfufgT29ljP5Dnwq7+HV6W5FslmRj7ny/Wa/p6HbjA7QcN67fVlsRMzKc3Qxc6ovqRDJOjw5ZB+GF/W0O004N3ztb4DCaJ4qoS+2mkn7U/nbcALtconOU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
