travis:
  secure:
    BINSTAR_TOKEN: U/BAl/DBuKtQzkRnb1LdXSa99Pl9mGEQ5ZvGwBmeXPUgNnc+zRabVG4hmJfXbknmhthwiNSJnHZVMfBtk/8mldsc4JVNmP3DtPNk0sHxLPcGW31ApESNqstePUv3frAFHeco/j1ZGInUF35/Bq0tS678AsKao2va9i2sGWp/S1JvuDEJPjSp2DTSnbPfABrmdASk5RcfJDihsofTfIzZOPtxWw7eF/vWQ723TmCaPnrlrh1D5GdA1e+misTJflfIP9sexn4qQVyWO3Wm31qM2HVwqzpCmTLPnT115Yv0sGvZZhY+zZdh6h6LbJQq7Hz5T+1Mca++fvToSlqWIagBktvpFs/SaKsd8aJamQrruFSZlZqTz1XqPzapI35XRfPrw5QZlaCGH3jFF9ePmqcmD+SsAoz/WGsxehGDXV8v/8AA+BEk45mXxuKDS3nXg9pdfq0c4TjhypkkQuNas+fNPUjGhUjPY6txBjzjWdcqxlXVpfH2uDppBMJLMbVjkZfxYxm2akWh0iAyXmUjJw3D1OybkTgqMnu3JnGf1wncqN86pLqQuiwouyjHxLMSKtb3o1/4I2AL6FCgUvChh5brvG9fa5p9idClhIKQJxWF5Ec8iksK4DC4hK+tBkFmefNcD6hw9rjUZhl/LmBMMvQHcbSGTBTyQNsGrecZevMo90w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
