travis:
  secure:
    BINSTAR_TOKEN: ZtjR3BKwtyfwkN7Yq34kYC4F658UXvn2fhDU4DXR7gOLeHku+lw1OZyW7U5XkrU7Ta2v/SryQiJ0gO+BwAa2A24UeF1jEMCK7mU9vqJQEE5/wZOP/1cysrwvBxsKWWqYXn/0J28hN/hPtDVGdAtteMXrGPkkUhRprF2Us5LUhLC1uUwERLhjOvHjjKW4U+egEqRpEAo2zWXzV5emfeREsNQKtbRZamADJri1Il4XBVPNklr6zEsM43QHaPjJc0DsMjt65u2Tk8jc40o4Ba61MB4J9IsZsWQC6EvTQOmHCEBCdvX2DDg+jc8ibPZlDe0rBpJoFx47uM/M4je3XcVYj+xK+JCjnefEnuhMsCBC0sY0buAlLojdm+kXNdOpMyLnPYzadF4yXGYCt0fP3wGBulRv/u7jGpimO+XLVBQU3vM55Q9ByV+/oXuXxiYw1tXm6BP9cf86RHuTlLVAjVKEkNTl14/pafolq3bbiJRxeK/5uFrIPV5ipTZPQKiwHajcicJZZ71hJpsIyEwZsyxMphPuQTdxHGnQs/M7Ep8YPkKqr7yrPoAweI9I89kHNkqW4OubS3LiN6/tVqeUmjG/6Tp9Ol/5xzvnKO4/kY+aaZWaf1ibBT/DhimdwbUvSBPJTMwRd6u+KE9qijyouQPS446Wo7eb+AQn60VAKs3gSrk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
